In [ ]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.5.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.0)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.5.0-py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.9/400.9 kB 8.5 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.5.0

In [ ]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']
df = pd.read_csv(url, names=columns)
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df[['Insulin','Glucose','BloodPressure','SkinThickness','BMI','DiabetesPedigreeFunction','Age']].replace(0, np.nan, inplace=True)

/tmp/ipython-input-3606440048.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[['Insulin','Glucose','BloodPressure','SkinThickness','BMI','DiabetesPedigreeFunction','Age']].replace(0, np.nan, inplace=True)

In [ ]:
df.fillna(df.mean(),inplace=True)

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 50, 200)
    max_depth = trial.suggest_int("max_depth", 5, 20)

    model = RandomForestClassifier(
        n_estimators = n_estimators,
        max_depth = max_depth,
        random_state = 42
    )

    score = cross_val_score(model, X_train, y_train, cv=5, scoring="accuracy").mean()
    return score

In [ ]:
study = optuna.create_study(direction = 'maximize', sampler = optuna.samplers.TPESampler())
study.optimize(objective, n_trials=50)

[I 2025-10-29 15:27:23,956] A new study created in memory with name: no-name-4a085072-9e59-48dc-8e78-af13e5e6f148
[I 2025-10-29 15:27:25,686] Trial 0 finished with value: 0.7655071304811407 and parameters: {'n_estimators': 152, 'max_depth': 10}. Best is trial 0 with value: 0.7655071304811407.
[I 2025-10-29 15:27:26,721] Trial 1 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 52, 'max_depth': 8}. Best is trial 1 with value: 0.7703985072637611.
[I 2025-10-29 15:27:32,546] Trial 2 finished with value: 0.7687325069972012 and parameters: {'n_estimators': 185, 'max_depth': 9}. Best is trial 1 with value: 0.7703985072637611.
[I 2025-10-29 15:27:35,396] Trial 3 finished with value: 0.7736505397840864 and parameters: {'n_estimators': 122, 'max_depth': 5}. Best is trial 3 with value: 0.7736505397840864.
[I 2025-10-29 15:27:37,962] Trial 4 finished with value: 0.7866853258696522 and parameters: {'n_estimators': 91, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:39,588] Trial 5 finished with value: 0.7720645075303212 and parameters: {'n_estimators': 72, 'max_depth': 9}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:45,283] Trial 6 finished with value: 0.7785285885645742 and parameters: {'n_estimators': 184, 'max_depth': 19}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:46,457] Trial 7 finished with value: 0.7834466213514595 and parameters: {'n_estimators': 115, 'max_depth': 13}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:47,151] Trial 8 finished with value: 0.7736638677862189 and parameters: {'n_estimators': 70, 'max_depth': 9}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:47,789] Trial 9 finished with value: 0.7801945888311342 and parameters: {'n_estimators': 60, 'max_depth': 12}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:48,854] Trial 10 finished with value: 0.7753032120485139 and parameters: {'n_estimators': 103, 'max_depth': 17}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:49,927] Trial 11 finished with value: 0.7801812608290016 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:51,387] Trial 12 finished with value: 0.7736638677862189 and parameters: {'n_estimators': 143, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:52,351] Trial 13 finished with value: 0.7753298680527789 and parameters: {'n_estimators': 94, 'max_depth': 13}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:53,657] Trial 14 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 127, 'max_depth': 16}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:55,485] Trial 15 finished with value: 0.7687458349993336 and parameters: {'n_estimators': 119, 'max_depth': 12}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:56,686] Trial 16 finished with value: 0.7736771957883514 and parameters: {'n_estimators': 84, 'max_depth': 18}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:58,378] Trial 17 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 163, 'max_depth': 20}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:27:59,536] Trial 18 finished with value: 0.783433293349327 and parameters: {'n_estimators': 111, 'max_depth': 11}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:00,887] Trial 19 finished with value: 0.7801812608290017 and parameters: {'n_estimators': 132, 'max_depth': 15}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:01,721] Trial 20 finished with value: 0.7769025723044116 and parameters: {'n_estimators': 84, 'max_depth': 7}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:02,820] Trial 21 finished with value: 0.7752632280421164 and parameters: {'n_estimators': 107, 'max_depth': 11}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:03,985] Trial 22 finished with value: 0.7850593096094897 and parameters: {'n_estimators': 113, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:05,420] Trial 23 finished with value: 0.7736638677862189 and parameters: {'n_estimators': 137, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:06,421] Trial 24 finished with value: 0.7801812608290017 and parameters: {'n_estimators': 93, 'max_depth': 16}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:08,301] Trial 25 finished with value: 0.7834332933493269 and parameters: {'n_estimators': 118, 'max_depth': 13}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:09,380] Trial 26 finished with value: 0.7850593096094897 and parameters: {'n_estimators': 83, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:10,222] Trial 27 finished with value: 0.775303212048514 and parameters: {'n_estimators': 81, 'max_depth': 17}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:10,979] Trial 28 finished with value: 0.7850593096094896 and parameters: {'n_estimators': 72, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:12,464] Trial 29 finished with value: 0.7785285885645742 and parameters: {'n_estimators': 147, 'max_depth': 11}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:14,115] Trial 30 finished with value: 0.7736372117819539 and parameters: {'n_estimators': 159, 'max_depth': 15}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:14,871] Trial 31 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 69, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:15,488] Trial 32 finished with value: 0.7834199653471945 and parameters: {'n_estimators': 59, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:16,443] Trial 33 finished with value: 0.7801812608290019 and parameters: {'n_estimators': 92, 'max_depth': 16}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:17,009] Trial 34 finished with value: 0.7850859656137545 and parameters: {'n_estimators': 53, 'max_depth': 12}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:17,554] Trial 35 finished with value: 0.7703851792616286 and parameters: {'n_estimators': 52, 'max_depth': 10}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:18,395] Trial 36 finished with value: 0.7720378515260563 and parameters: {'n_estimators': 81, 'max_depth': 12}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:19,105] Trial 37 finished with value: 0.783406637345062 and parameters: {'n_estimators': 61, 'max_depth': 7}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:21,927] Trial 38 finished with value: 0.7720111955217912 and parameters: {'n_estimators': 196, 'max_depth': 10}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:22,942] Trial 39 finished with value: 0.7785685725709717 and parameters: {'n_estimators': 98, 'max_depth': 13}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:23,502] Trial 40 finished with value: 0.7785285885645742 and parameters: {'n_estimators': 51, 'max_depth': 17}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:24,223] Trial 41 finished with value: 0.7720378515260563 and parameters: {'n_estimators': 68, 'max_depth': 15}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:25,000] Trial 42 finished with value: 0.7866853258696522 and parameters: {'n_estimators': 76, 'max_depth': 14}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:25,811] Trial 43 finished with value: 0.7720245235239237 and parameters: {'n_estimators': 78, 'max_depth': 12}. Best is trial 4 with value: 0.7866853258696522.
[I 2025-10-29 15:28:26,457] Trial 44 finished with value: 0.786711981873917 and parameters: {'n_estimators': 61, 'max_depth': 13}. Best is trial 44 with value: 0.786711981873917.
[I 2025-10-29 15:28:27,097] Trial 45 finished with value: 0.7850859656137545 and parameters: {'n_estimators': 62, 'max_depth': 11}. Best is trial 44 with value: 0.786711981873917.
[I 2025-10-29 15:28:27,750] Trial 46 finished with value: 0.776915900306544 and parameters: {'n_estimators': 62, 'max_depth': 9}. Best is trial 44 with value: 0.786711981873917.
[I 2025-10-29 15:28:28,349] Trial 47 finished with value: 0.7866719978675196 and parameters: {'n_estimators': 56, 'max_depth': 11}. Best is trial 44 with value: 0.786711981873917.
[I 2025-10-29 15:28:28,901] Trial 48 finished with value: 0.7703851792616286 and parameters: {'n_estimators': 55, 'max_depth': 8}. Best is trial 44 with value: 0.786711981873917.
[I 2025-10-29 15:28:29,735] Trial 49 finished with value: 0.765480474476876 and parameters: {'n_estimators': 73, 'max_depth': 10}. Best is trial 44 with value: 0.786711981873917.

In [ ]:
print(f'Best Trial Accuracy achieved: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best Trial Accuracy achieved: 0.786711981873917
Best hyperparameters: {'n_estimators': 61, 'max_depth': 13}

In [ ]:
from sklearn.metrics import accuracy_score

# Now using the best parameters determined using CV to get best results

final_model = RandomForestClassifier(**study.best_trial.params,random_state=42)
final_model.fit(X_train,y_train)

y_pred = final_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy of Testing using best params: {accuracy}')

Accuracy of Testing using best params: 0.7467532467532467

Using Different Samplers (GridSearch and RandomSearch)

In [ ]:
# Random search
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)

[I 2025-10-29 15:28:29,920] A new study created in memory with name: no-name-1e883187-52c6-4a4b-9fd6-aa6d1674bde7
[I 2025-10-29 15:28:31,477] Trial 0 finished with value: 0.7720245235239237 and parameters: {'n_estimators': 147, 'max_depth': 14}. Best is trial 0 with value: 0.7720245235239237.
[I 2025-10-29 15:28:33,768] Trial 1 finished with value: 0.7736638677862189 and parameters: {'n_estimators': 140, 'max_depth': 13}. Best is trial 1 with value: 0.7736638677862189.
[I 2025-10-29 15:28:35,196] Trial 2 finished with value: 0.7703718512594963 and parameters: {'n_estimators': 131, 'max_depth': 12}. Best is trial 1 with value: 0.7736638677862189.
[I 2025-10-29 15:28:37,155] Trial 3 finished with value: 0.7703585232573638 and parameters: {'n_estimators': 198, 'max_depth': 9}. Best is trial 1 with value: 0.7736638677862189.
[I 2025-10-29 15:28:38,711] Trial 4 finished with value: 0.7687458349993337 and parameters: {'n_estimators': 164, 'max_depth': 7}. Best is trial 1 with value: 0.7736638677862189.
[I 2025-10-29 15:28:40,399] Trial 5 finished with value: 0.7704118352658936 and parameters: {'n_estimators': 178, 'max_depth': 6}. Best is trial 1 with value: 0.7736638677862189.
[I 2025-10-29 15:28:40,934] Trial 6 finished with value: 0.776915900306544 and parameters: {'n_estimators': 50, 'max_depth': 14}. Best is trial 6 with value: 0.776915900306544.
[I 2025-10-29 15:28:42,542] Trial 7 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 159, 'max_depth': 18}. Best is trial 6 with value: 0.776915900306544.
[I 2025-10-29 15:28:43,560] Trial 8 finished with value: 0.7687724910035985 and parameters: {'n_estimators': 99, 'max_depth': 12}. Best is trial 6 with value: 0.776915900306544.
[I 2025-10-29 15:28:44,166] Trial 9 finished with value: 0.7671598027455684 and parameters: {'n_estimators': 50, 'max_depth': 9}. Best is trial 6 with value: 0.776915900306544.
[I 2025-10-29 15:28:45,022] Trial 10 finished with value: 0.7785285885645742 and parameters: {'n_estimators': 54, 'max_depth': 7}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:47,228] Trial 11 finished with value: 0.7687591630014661 and parameters: {'n_estimators': 172, 'max_depth': 7}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:48,616] Trial 12 finished with value: 0.7736505397840864 and parameters: {'n_estimators': 137, 'max_depth': 16}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:50,153] Trial 13 finished with value: 0.7687458349993337 and parameters: {'n_estimators': 159, 'max_depth': 7}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:50,909] Trial 14 finished with value: 0.7736771957883514 and parameters: {'n_estimators': 73, 'max_depth': 9}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:51,798] Trial 15 finished with value: 0.7752765560442489 and parameters: {'n_estimators': 89, 'max_depth': 8}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:53,524] Trial 16 finished with value: 0.7687591630014661 and parameters: {'n_estimators': 169, 'max_depth': 14}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:55,019] Trial 17 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 141, 'max_depth': 17}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:56,882] Trial 18 finished with value: 0.7736638677862189 and parameters: {'n_estimators': 171, 'max_depth': 11}. Best is trial 10 with value: 0.7785285885645742.
[I 2025-10-29 15:28:58,636] Trial 19 finished with value: 0.7785552445688391 and parameters: {'n_estimators': 111, 'max_depth': 19}. Best is trial 19 with value: 0.7785552445688391.
[I 2025-10-29 15:28:59,762] Trial 20 finished with value: 0.7818339330934293 and parameters: {'n_estimators': 91, 'max_depth': 13}. Best is trial 20 with value: 0.7818339330934293.
[I 2025-10-29 15:29:01,415] Trial 21 finished with value: 0.7704118352658936 and parameters: {'n_estimators': 177, 'max_depth': 6}. Best is trial 20 with value: 0.7818339330934293.
[I 2025-10-29 15:29:03,009] Trial 22 finished with value: 0.7752898840463814 and parameters: {'n_estimators': 158, 'max_depth': 11}. Best is trial 20 with value: 0.7818339330934293.
[I 2025-10-29 15:29:03,993] Trial 23 finished with value: 0.7736505397840864 and parameters: {'n_estimators': 96, 'max_depth': 12}. Best is trial 20 with value: 0.7818339330934293.
[I 2025-10-29 15:29:05,825] Trial 24 finished with value: 0.7687325069972012 and parameters: {'n_estimators': 185, 'max_depth': 9}. Best is trial 20 with value: 0.7818339330934293.
[I 2025-10-29 15:29:07,119] Trial 25 finished with value: 0.7736638677862187 and parameters: {'n_estimators': 138, 'max_depth': 6}. Best is trial 20 with value: 0.7818339330934293.
[I 2025-10-29 15:29:08,109] Trial 26 finished with value: 0.7736771957883514 and parameters: {'n_estimators': 98, 'max_depth': 20}. Best is trial 20 with value: 0.7818339330934293.
[I 2025-10-29 15:29:08,727] Trial 27 finished with value: 0.783459949353592 and parameters: {'n_estimators': 59, 'max_depth': 16}. Best is trial 27 with value: 0.783459949353592.
[I 2025-10-29 15:29:10,620] Trial 28 finished with value: 0.7769025723044115 and parameters: {'n_estimators': 131, 'max_depth': 20}. Best is trial 27 with value: 0.783459949353592.
[I 2025-10-29 15:29:11,856] Trial 29 finished with value: 0.776915900306544 and parameters: {'n_estimators': 83, 'max_depth': 8}. Best is trial 27 with value: 0.783459949353592.
[I 2025-10-29 15:29:12,575] Trial 30 finished with value: 0.7753165400506464 and parameters: {'n_estimators': 69, 'max_depth': 13}. Best is trial 27 with value: 0.783459949353592.
[I 2025-10-29 15:29:13,475] Trial 31 finished with value: 0.7785552445688391 and parameters: {'n_estimators': 87, 'max_depth': 20}. Best is trial 27 with value: 0.783459949353592.
[I 2025-10-29 15:29:14,992] Trial 32 finished with value: 0.7883246701319473 and parameters: {'n_estimators': 106, 'max_depth': 14}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:17,352] Trial 33 finished with value: 0.7687458349993337 and parameters: {'n_estimators': 166, 'max_depth': 7}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:19,358] Trial 34 finished with value: 0.7752632280421164 and parameters: {'n_estimators': 198, 'max_depth': 17}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:20,334] Trial 35 finished with value: 0.7785552445688392 and parameters: {'n_estimators': 94, 'max_depth': 18}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:21,630] Trial 36 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 129, 'max_depth': 11}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:24,452] Trial 37 finished with value: 0.7769025723044115 and parameters: {'n_estimators': 185, 'max_depth': 17}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:26,117] Trial 38 finished with value: 0.7703851792616286 and parameters: {'n_estimators': 164, 'max_depth': 20}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:26,789] Trial 39 finished with value: 0.7818072770891644 and parameters: {'n_estimators': 70, 'max_depth': 7}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:28,035] Trial 40 finished with value: 0.7687858190057311 and parameters: {'n_estimators': 134, 'max_depth': 6}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:29,293] Trial 41 finished with value: 0.7736505397840864 and parameters: {'n_estimators': 138, 'max_depth': 5}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:30,018] Trial 42 finished with value: 0.7850992936158872 and parameters: {'n_estimators': 72, 'max_depth': 13}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:30,945] Trial 43 finished with value: 0.7818072770891644 and parameters: {'n_estimators': 90, 'max_depth': 15}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:31,603] Trial 44 finished with value: 0.7850859656137545 and parameters: {'n_estimators': 62, 'max_depth': 11}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:33,417] Trial 45 finished with value: 0.7671064907370384 and parameters: {'n_estimators': 183, 'max_depth': 9}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:35,437] Trial 46 finished with value: 0.7720245235239237 and parameters: {'n_estimators': 155, 'max_depth': 14}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:37,342] Trial 47 finished with value: 0.7736505397840864 and parameters: {'n_estimators': 148, 'max_depth': 8}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:38,763] Trial 48 finished with value: 0.7720245235239237 and parameters: {'n_estimators': 138, 'max_depth': 17}. Best is trial 32 with value: 0.7883246701319473.
[I 2025-10-29 15:29:40,079] Trial 49 finished with value: 0.7752765560442489 and parameters: {'n_estimators': 134, 'max_depth': 8}. Best is trial 32 with value: 0.7883246701319473.

In [ ]:
from sklearn.metrics import accuracy_score

# Now using the best parameters determined using CV to get best results

final_model = RandomForestClassifier(**study.best_trial.params,random_state=42)
final_model.fit(X_train,y_train)

y_pred = final_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy of Testing using best params: {accuracy}')

Accuracy of Testing using best params: 0.7272727272727273

In [ ]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [ ]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective, n_trials=50)

[I 2025-10-29 15:29:40,365] A new study created in memory with name: no-name-00175ac5-4bb5-4467-bdad-64be5be165ae
[I 2025-10-29 15:29:41,301] Trial 0 finished with value: 0.7687458349993335 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7687458349993335.
[I 2025-10-29 15:29:42,821] Trial 1 finished with value: 0.7655071304811407 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7687458349993335.
[I 2025-10-29 15:29:43,347] Trial 2 finished with value: 0.7752765560442489 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7752765560442489.
[I 2025-10-29 15:29:44,377] Trial 3 finished with value: 0.7801812608290016 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:29:45,451] Trial 4 finished with value: 0.775303212048514 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:29:45,989] Trial 5 finished with value: 0.7720245235239236 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:29:47,720] Trial 6 finished with value: 0.7703718512594963 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:29:49,830] Trial 7 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:29:52,210] Trial 8 finished with value: 0.7785419165667067 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:29:56,626] Trial 9 finished with value: 0.7671331467413035 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:30:02,897] Trial 10 finished with value: 0.7785285885645742 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:30:04,961] Trial 11 finished with value: 0.7703851792616287 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:30:06,755] Trial 12 finished with value: 0.7703985072637611 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:30:07,237] Trial 13 finished with value: 0.767146474743436 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:30:08,249] Trial 14 finished with value: 0.7671331467413035 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 3 with value: 0.7801812608290016.
[I 2025-10-29 15:30:08,766] Trial 15 finished with value: 0.7801679328268692 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 3 with value: 0.7801812608290016.

In [ ]:
from sklearn.metrics import accuracy_score

# Now using the best parameters determined using CV to get best results

final_model = RandomForestClassifier(**study.best_trial.params,random_state=42)
final_model.fit(X_train,y_train)

y_pred = final_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy of Testing using best params: {accuracy}')

Accuracy of Testing using best params: 0.7337662337662337

Visualisations using PLOTS

In [ ]:
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

Visualising the study of Bayesian CV

In [ ]:
plot_optimization_history(study).show()

In [ ]:
plot_parallel_coordinate(study).show()

In [ ]:
plot_slice(study).show()

In [ ]:
plot_contour(study).show()

In [ ]:
plot_param_importances(study).show()

HyperParameter Tuning with Multiple ML Models

In [ ]:
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [ ]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [ ]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=200)

[I 2025-10-29 15:30:11,962] A new study created in memory with name: no-name-6f41a16e-5be8-406b-b796-86c7784d8dc5
[I 2025-10-29 15:30:13,351] Trial 0 finished with value: 0.7654471544715448 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 93, 'learning_rate': 0.05621855601844021, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 0 with value: 0.7654471544715448.
[I 2025-10-29 15:30:16,372] Trial 1 finished with value: 0.760569105691057 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 146, 'learning_rate': 0.0927766030961277, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.7654471544715448.
[I 2025-10-29 15:30:16,925] Trial 2 finished with value: 0.7752351347042882 and parameters: {'classifier': 'RandomForest', 'n_estimators': 102, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:17,534] Trial 3 finished with value: 0.7687230989956958 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 99, 'learning_rate': 0.13465331700643113, 'max_depth': 3, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:17,581] Trial 4 finished with value: 0.768675274988044 and parameters: {'classifier': 'SVM', 'C': 1.5896246063372483, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:23,749] Trial 5 finished with value: 0.7524549657261278 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 297, 'learning_rate': 0.08269706621444586, 'max_depth': 14, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:23,789] Trial 6 finished with value: 0.7703092619161486 and parameters: {'classifier': 'SVM', 'C': 0.16104292574626644, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:24,495] Trial 7 finished with value: 0.7752271640363463 and parameters: {'classifier': 'RandomForest', 'n_estimators': 132, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:26,489] Trial 8 finished with value: 0.7752271640363463 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 218, 'learning_rate': 0.022040518011873438, 'max_depth': 4, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:28,109] Trial 9 finished with value: 0.7670970827355332 and parameters: {'classifier': 'RandomForest', 'n_estimators': 238, 'max_depth': 20, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:28,372] Trial 10 finished with value: 0.7735852064402997 and parameters: {'classifier': 'RandomForest', 'n_estimators': 51, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:29,174] Trial 11 finished with value: 0.771967160848079 and parameters: {'classifier': 'RandomForest', 'n_estimators': 148, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:29,772] Trial 12 finished with value: 0.7703331739199745 and parameters: {'classifier': 'RandomForest', 'n_estimators': 109, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:30,827] Trial 13 finished with value: 0.7670811413996493 and parameters: {'classifier': 'RandomForest', 'n_estimators': 198, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:31,654] Trial 14 finished with value: 0.7735931771082417 and parameters: {'classifier': 'RandomForest', 'n_estimators': 147, 'max_depth': 16, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:32,024] Trial 15 finished with value: 0.7670891120675912 and parameters: {'classifier': 'RandomForest', 'n_estimators': 82, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:32,345] Trial 16 finished with value: 0.7605850470269409 and parameters: {'classifier': 'RandomForest', 'n_estimators': 50, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:32,413] Trial 17 finished with value: 0.7149689143950263 and parameters: {'classifier': 'SVM', 'C': 88.02405241826843, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:33,387] Trial 18 finished with value: 0.7735931771082417 and parameters: {'classifier': 'RandomForest', 'n_estimators': 174, 'max_depth': 17, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 2 with value: 0.7752351347042882.
[I 2025-10-29 15:30:33,920] Trial 19 finished with value: 0.788243264785589 and parameters: {'classifier': 'RandomForest', 'n_estimators': 119, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:34,261] Trial 20 finished with value: 0.7150007970667942 and parameters: {'classifier': 'SVM', 'C': 98.24769174073947, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:34,824] Trial 21 finished with value: 0.7866172485254265 and parameters: {'classifier': 'RandomForest', 'n_estimators': 124, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:35,403] Trial 22 finished with value: 0.776837238960625 and parameters: {'classifier': 'RandomForest', 'n_estimators': 123, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:35,955] Trial 23 finished with value: 0.7703570859238004 and parameters: {'classifier': 'RandomForest', 'n_estimators': 127, 'max_depth': 5, 'min_samples_split': 10, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:36,764] Trial 24 finished with value: 0.7800972421488921 and parameters: {'classifier': 'RandomForest', 'n_estimators': 176, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:37,679] Trial 25 finished with value: 0.7800972421488921 and parameters: {'classifier': 'RandomForest', 'n_estimators': 179, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:38,879] Trial 26 finished with value: 0.776837238960625 and parameters: {'classifier': 'RandomForest', 'n_estimators': 173, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:40,285] Trial 27 finished with value: 0.7735852064402997 and parameters: {'classifier': 'RandomForest', 'n_estimators': 220, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:41,478] Trial 28 finished with value: 0.7784632552207875 and parameters: {'classifier': 'RandomForest', 'n_estimators': 265, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:41,518] Trial 29 finished with value: 0.692140921409214 and parameters: {'classifier': 'SVM', 'C': 4.060829028086308, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:41,972] Trial 30 finished with value: 0.7703570859238004 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 74, 'learning_rate': 0.2769547806495929, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:42,842] Trial 31 finished with value: 0.7784712258887295 and parameters: {'classifier': 'RandomForest', 'n_estimators': 190, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:43,629] Trial 32 finished with value: 0.7800972421488921 and parameters: {'classifier': 'RandomForest', 'n_estimators': 171, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:44,392] Trial 33 finished with value: 0.7768531802965088 and parameters: {'classifier': 'RandomForest', 'n_estimators': 160, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:45,298] Trial 34 finished with value: 0.7784632552207875 and parameters: {'classifier': 'RandomForest', 'n_estimators': 194, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:45,863] Trial 35 finished with value: 0.7784552845528455 and parameters: {'classifier': 'RandomForest', 'n_estimators': 121, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:47,775] Trial 36 finished with value: 0.7621712099473936 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 214, 'learning_rate': 0.011021134154720408, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:48,532] Trial 37 finished with value: 0.7833492746692173 and parameters: {'classifier': 'RandomForest', 'n_estimators': 161, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:50,065] Trial 38 finished with value: 0.7621871512832775 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 156, 'learning_rate': 0.026070759503202572, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 10}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:50,138] Trial 39 finished with value: 0.7166188426590149 and parameters: {'classifier': 'SVM', 'C': 0.1141851533759919, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:50,748] Trial 40 finished with value: 0.7719591901801371 and parameters: {'classifier': 'RandomForest', 'n_estimators': 84, 'max_depth': 11, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:51,746] Trial 41 finished with value: 0.7752191933684043 and parameters: {'classifier': 'RandomForest', 'n_estimators': 136, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:52,579] Trial 42 finished with value: 0.7703331739199745 and parameters: {'classifier': 'RandomForest', 'n_estimators': 114, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:53,342] Trial 43 finished with value: 0.7784791965566714 and parameters: {'classifier': 'RandomForest', 'n_estimators': 162, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:53,977] Trial 44 finished with value: 0.7752032520325204 and parameters: {'classifier': 'RandomForest', 'n_estimators': 139, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:54,854] Trial 45 finished with value: 0.7817073170731708 and parameters: {'classifier': 'RandomForest', 'n_estimators': 185, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:55,757] Trial 46 finished with value: 0.7800813008130082 and parameters: {'classifier': 'RandomForest', 'n_estimators': 186, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:57,657] Trial 47 finished with value: 0.7524469950581859 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 206, 'learning_rate': 0.2884517812322058, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 10}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:58,096] Trial 48 finished with value: 0.7622270046229874 and parameters: {'classifier': 'RandomForest', 'n_estimators': 100, 'max_depth': 4, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:59,248] Trial 49 finished with value: 0.7735931771082417 and parameters: {'classifier': 'RandomForest', 'n_estimators': 252, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:30:59,304] Trial 50 finished with value: 0.7459588713534194 and parameters: {'classifier': 'SVM', 'C': 8.713345205361163, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:00,217] Trial 51 finished with value: 0.7817312290769967 and parameters: {'classifier': 'RandomForest', 'n_estimators': 187, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:00,934] Trial 52 finished with value: 0.776829268292683 and parameters: {'classifier': 'RandomForest', 'n_estimators': 153, 'max_depth': 11, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:01,981] Trial 53 finished with value: 0.7800972421488921 and parameters: {'classifier': 'RandomForest', 'n_estimators': 234, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:03,125] Trial 54 finished with value: 0.7800972421488921 and parameters: {'classifier': 'RandomForest', 'n_estimators': 203, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:04,492] Trial 55 finished with value: 0.7817232584090547 and parameters: {'classifier': 'RandomForest', 'n_estimators': 183, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:05,416] Trial 56 finished with value: 0.776837238960625 and parameters: {'classifier': 'RandomForest', 'n_estimators': 143, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:06,225] Trial 57 finished with value: 0.7784712258887295 and parameters: {'classifier': 'RandomForest', 'n_estimators': 164, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:07,183] Trial 58 finished with value: 0.7800892714809501 and parameters: {'classifier': 'RandomForest', 'n_estimators': 185, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:08,324] Trial 59 finished with value: 0.7540570699824646 and parameters: {'classifier': 'RandomForest', 'n_estimators': 227, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:08,369] Trial 60 finished with value: 0.7344571975131515 and parameters: {'classifier': 'SVM', 'C': 0.735159214253473, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:09,267] Trial 61 finished with value: 0.7784712258887295 and parameters: {'classifier': 'RandomForest', 'n_estimators': 180, 'max_depth': 11, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:10,215] Trial 62 finished with value: 0.7752271640363463 and parameters: {'classifier': 'RandomForest', 'n_estimators': 209, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:11,062] Trial 63 finished with value: 0.7752191933684043 and parameters: {'classifier': 'RandomForest', 'n_estimators': 169, 'max_depth': 10, 'min_samples_split': 10, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:12,017] Trial 64 finished with value: 0.7719512195121951 and parameters: {'classifier': 'RandomForest', 'n_estimators': 198, 'max_depth': 9, 'min_samples_split': 9, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:12,561] Trial 65 finished with value: 0.7703411445879165 and parameters: {'classifier': 'RandomForest', 'n_estimators': 114, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:13,260] Trial 66 finished with value: 0.7605850470269409 and parameters: {'classifier': 'RandomForest', 'n_estimators': 130, 'max_depth': 11, 'min_samples_split': 6, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:14,953] Trial 67 finished with value: 0.7638211382113821 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 148, 'learning_rate': 0.0269129314752356, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 8}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:16,830] Trial 68 finished with value: 0.7817232584090547 and parameters: {'classifier': 'RandomForest', 'n_estimators': 180, 'max_depth': 9, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:18,685] Trial 69 finished with value: 0.7735852064402997 and parameters: {'classifier': 'RandomForest', 'n_estimators': 195, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:19,092] Trial 70 finished with value: 0.7687071576598119 and parameters: {'classifier': 'RandomForest', 'n_estimators': 90, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.
[I 2025-10-29 15:31:19,961] Trial 71 finished with value: 0.7817232584090547 and parameters: {'classifier': 'RandomForest', 'n_estimators': 178, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 19 with value: 0.788243264785589.

In [ ]:
best_trial = study.best_trial
print(f'Best Trial Accuracy achieved: {best_trial.value}')
print(f'Best hyperparameters: {best_trial.params}')

Best Trial Accuracy achieved: 0.7915032679738562
Best hyperparameters: {'classifier': 'RandomForest', 'n_estimators': 65, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}

In [ ]:
studyDF=study.trials_dataframe()

In [ ]:
studyDF.head()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.765447,2025-10-29 15:30:11.964091,2025-10-29 15:30:13.351222,0 days 00:00:01.387131,NaN,NaN,GradientBoosting,NaN,NaN,0.056219,8.0,10.0,5.0,93.0,COMPLETE
1,1,0.760569,2025-10-29 15:30:13.352255,2025-10-29 15:30:16.372032,0 days 00:00:03.019777,NaN,NaN,GradientBoosting,NaN,NaN,0.092777,11.0,5.0,10.0,146.0,COMPLETE
2,2,0.775235,2025-10-29 15:30:16.372945,2025-10-29 15:30:16.925131,0 days 00:00:00.552186,NaN,True,RandomForest,NaN,NaN,NaN,7.0,5.0,9.0,102.0,COMPLETE
3,3,0.768723,2025-10-29 15:30:16.926002,2025-10-29 15:30:17.533922,0 days 00:00:00.607920,NaN,NaN,GradientBoosting,NaN,NaN,0.134653,3.0,1.0,3.0,99.0,COMPLETE
4,4,0.768675,2025-10-29 15:30:17.535127,2025-10-29 15:30:17.581257,0 days 00:00:00.046130,1.589625,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [ ]:
studyDF['params_classifier'].value_counts()

params_classifier
RandomForest        172
GradientBoosting     15
SVM                  13
Name: count, dtype: int64

In [ ]:
studyDF['value'].groupby(studyDF['params_classifier']).mean()

params_classifier
GradientBoosting    0.761223
RandomForest        0.780705
SVM                 0.735137
Name: value, dtype: float64